FROM openjdk
MAINTAINER lgomezs lmgomez.saavedra@gmail.com
ADD target/category-product-service.jar category-product-service.jar
ENTRYPOINT ["java", "-jar", "/category-product-service.jar"]
EXPOSE 2222